;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
;   https://docs.platformio.org/page/projectconf.html

[platformio]

; ==================== Actuator ====================

; !Haptic driver
; src_dir = examples/actuator/aw86224_full
; src_dir = examples/actuator/drv2605_effect
; src_dir = examples/actuator/drv2605_full

; !LED driver
; src_dir = examples/actuator/aw9364_led

; ==================== IO ====================

; !GPIO expander
; src_dir = examples/io/pca9570_expander
; src_dir = examples/io/xl9555_backlight
; src_dir = examples/io/xl9555_interrupt
; src_dir = examples/io/xl9555_read
; src_dir = examples/io/xl9555_spi
; src_dir = examples/io/xl9555_write

; ==================== Power ====================

; !Gauge
; src_dir = examples/power/axp2602_gauge
; src_dir = examples/power/axp2602_gauge_udp
; src_dir = examples/power/bq27220_gauge

; !PMIC
; src_dir = examples/power/axp192_basic
; src_dir = examples/power/axp192_irq
; src_dir = examples/power/axp202_basic
; src_dir = examples/power/axp202_irq
; src_dir = examples/power/axp2101_basic
; src_dir = examples/power/axp2101_irq
; src_dir = examples/power/axp517_basic
; src_dir = examples/power/axp517_bc12
; src_dir = examples/power/axp517_charger
; src_dir = examples/power/axp517_charger_web_monitor
; src_dir = examples/power/axp517_interrupt
; src_dir = examples/power/axp517_led
; src_dir = examples/power/axp517_pd_auto_request
src_dir = examples/power/axp517_pd_voltage
; src_dir = examples/power/axp517_power
; src_dir = examples/power/bq25896_charger
; src_dir = examples/power/bq25896_charger_web_monitor
; src_dir = examples/power/pmic_probe
; src_dir = examples/power/sy6970_charger
; src_dir = examples/power/sy6970_charger_web_monitor

; ==================== Sensor ====================

; !Accelerometer
; src_dir = examples/sensor/bma422_accelerometer
; src_dir = examples/sensor/bma422_any_motion
; src_dir = examples/sensor/bma422_no_motion
; src_dir = examples/sensor/bma423_accelerometer
; src_dir = examples/sensor/bma423_any_motion
; src_dir = examples/sensor/bma423_data_ready_interrupt
; src_dir = examples/sensor/bma423_no_motion
; src_dir = examples/sensor/bma423_step_activity
; src_dir = examples/sensor/bma423_step_detector
; src_dir = examples/sensor/bma423_tap
; src_dir = examples/sensor/bma423_tilt
; src_dir = examples/sensor/bma456h_accelerometer
; src_dir = examples/sensor/bma456h_any_motion
; src_dir = examples/sensor/bma456h_data_ready_interrupt
; src_dir = examples/sensor/bma456h_no_motion
; src_dir = examples/sensor/bma456h_step_activity
; src_dir = examples/sensor/bma456h_step_detector
; src_dir = examples/sensor/bma456h_tap
; src_dir = examples/sensor/bma_universal_compatibility

; !Finger navigation
; src_dir = examples/sensor/pawa350_motion

; !BHI260AP IMU
; src_dir = examples/sensor/bhi260ap_6dof
; src_dir = examples/sensor/bhi260ap_activity
; src_dir = examples/sensor/bhi260ap_aux_bmm150
; src_dir = examples/sensor/bhi260ap_aux_bmm150_bme280
; src_dir = examples/sensor/bhi260ap_aux_bmm150_bme280_gpio
; src_dir = examples/sensor/bhi260ap_aux_bmm150_euler
; src_dir = examples/sensor/bhi260ap_aux_bmm150_quaternion
; src_dir = examples/sensor/bhi260ap_euler
; src_dir = examples/sensor/bhi260ap_gpio
; src_dir = examples/sensor/bhi260ap_interrupt_settings
; src_dir = examples/sensor/bhi260ap_klio_recognition
; src_dir = examples/sensor/bhi260ap_klio_recognize_multiple
; src_dir = examples/sensor/bhi260ap_klio_self_learning
; src_dir = examples/sensor/bhi260ap_multiple
; src_dir = examples/sensor/bhi260ap_orientation
; src_dir = examples/sensor/bhi260ap_step_counter
; src_dir = examples/sensor/bhi260ap_tilt_detector
; src_dir = examples/sensor/bhi260ap_update_firmware

; !BHI360 IMU
; src_dir = examples/sensor/bhi360_6dof
; src_dir = examples/sensor/bhi360_any_motion
; src_dir = examples/sensor/bhi360_aux_bmm350_bme688_iaq
; src_dir = examples/sensor/bhi360_aux_bmm350_bmp580_bme688
; src_dir = examples/sensor/bhi360_aux_bmm350_euler
; src_dir = examples/sensor/bhi360_aux_bmm350_quaternion
; src_dir = examples/sensor/bhi360_euler
; src_dir = examples/sensor/bhi360_multi_tap
; src_dir = examples/sensor/bhi360_no_motion
; src_dir = examples/sensor/bhi360_step_counter

; !QMI8658 IMU
; src_dir = examples/sensor/qmi8658_advanced_features
; src_dir = examples/sensor/qmi8658_any_motion
; src_dir = examples/sensor/qmi8658_basic_read
; src_dir = examples/sensor/qmi8658_calibration
; src_dir = examples/sensor/qmi8658_fifo_read
; src_dir = examples/sensor/qmi8658_no_motion
; src_dir = examples/sensor/qmi8658_pedometer
; src_dir = examples/sensor/qmi8658_self_test
; src_dir = examples/sensor/qmi8658_sync_mode
; src_dir = examples/sensor/qmi8658_tap_detection
; src_dir = examples/sensor/qmi8658_wake_on_motion

; !QMI8658 deprecated API
; src_dir = examples/sensor/qmi8658_block_deprecated
; src_dir = examples/sensor/qmi8658_calibration_deprecated
; src_dir = examples/sensor/qmi8658_get_data_deprecated
; src_dir = examples/sensor/qmi8658_interrupt_block_deprecated
; src_dir = examples/sensor/qmi8658_interrupt_deprecated
; src_dir = examples/sensor/qmi8658_locking_mechanism_deprecated
; src_dir = examples/sensor/qmi8658_madgwick_ahrs_deprecated
; src_dir = examples/sensor/qmi8658_motion_detection_deprecated
; src_dir = examples/sensor/qmi8658_pedometer_deprecated
; src_dir = examples/sensor/qmi8658_read_from_fifo_deprecated
; src_dir = examples/sensor/qmi8658_tap_detection_deprecated
; src_dir = examples/sensor/qmi8658_wake_on_motion_callback_deprecated
; src_dir = examples/sensor/qmi8658_wake_on_motion_deprecated

; !Light sensor
; src_dir = examples/sensor/cm32181_light
; src_dir = examples/sensor/cm32181_light_interrupt
; src_dir = examples/sensor/ltr553als_sensor

; !Magnetometer
; src_dir = examples/sensor/bmm150_get_data
; src_dir = examples/sensor/mag_interface_get_data
; src_dir = examples/sensor/qmc5883l_get_data
; src_dir = examples/sensor/qmc5883p_get_data
; src_dir = examples/sensor/qmc6309_get_data
; src_dir = examples/sensor/qmc6310_calibrate
; src_dir = examples/sensor/qmc6310_compass
; src_dir = examples/sensor/qmc6310_get_data

; ==================== Touch ====================

; !Touch panel
; src_dir = examples/touch/chsc5816_get_point
; src_dir = examples/touch/cst3530_get_point
; src_dir = examples/touch/cst9217_get_point
; src_dir = examples/touch/cstxxx_get_point
; src_dir = examples/touch/ft6232_get_point
; src_dir = examples/touch/gt911_get_point
; src_dir = examples/touch/gt9895_gesture_lilygo_p4
; src_dir = examples/touch/gt9895_get_point
; src_dir = examples/touch/gt9895_get_point_lilygo_p4
; src_dir = examples/touch/hi8561_get_point_lilygo_p4
; src_dir = examples/touch/touch_interface

; ==================== RTC ====================

; !RTC
; src_dir = examples/rtc/pcf85063_alarm
; src_dir = examples/rtc/pcf85063_clock_output
; src_dir = examples/rtc/pcf85063_simple_time
; src_dir = examples/rtc/pcf8563_alarm
; src_dir = examples/rtc/pcf8563_clock_output
; src_dir = examples/rtc/pcf8563_simple_time
; src_dir = examples/rtc/pcf8563_time_lib
; src_dir = examples/rtc/pcf8563_time_sync
; src_dir = examples/rtc/rtc_helper
; src_dir = examples/rtc/rtc_posix

; ==================== Utility ====================

; !Utility
; src_dir = examples/utility/custom_callback
; src_dir = examples/utility/custom_callback_touch
; src_dir = examples/utility/wire_helper

; ==================== Default Config ====================

; !Device envs
; default_envs = esp32dev_arduino
default_envs = esp32s3_arduino
; default_envs = esp32c3_arduino
; default_envs = rp2040_arduino
; default_envs = nrf52840_arduino
; default_envs = stm32_arduino
; default_envs = pico_mbed

; !Test all
; default_envs = esp32dev_arduino , rp2040_arduino , nrf52840_arduino , stm32_arduino , pico_mbed

[env]
lib_extra_dirs = .
upload_speed = 921600
monitor_speed = 115200

build_flags =
    ; -DSENSOR_SDA=3
    ; -DSENSOR_SCL=2
    ; -DSENSOR_IRQ=-1

    ; -DPMIC_SDA=3
    ; -DPMIC_SCL=2
    ; -DPMIC_IRQ=21

    ; -DTOUCH_SDA=39
    ; -DTOUCH_SCL=40
    ; -DTOUCH_IRQ=3
    ; -DTOUCH_RST=9
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"

    ; -DARDUINO_T_DECK
    ; -DARDUINO_T_AMOLED_191
    ; -DARDUINO_T_AMOLED_191_QWIIC
    ; -DARDUINO_T_AMOLED_241
    ; -DARDUINO_T_AMOLED_147
    ; -DARDUINO_T_DISPLAY_S3_PRO
    ; -DARDUINO_T_DISPLAY_S3
    ; -DARDUINO_T_EPD47_S3
    ; -DARDUINO_T_WATCH_S3_ULTRA
    ; -DARDUINO_T_WATCH_S3
    ; -DARDUINO_T_DECK
    ; -DARDUINO_T_ULTIMA
    ; -DUSE_SPI_INTERFACE=1
    ; -DLOG_PORT=Serial
    ; -DBOSCH_PARSE_DATA_DUMP
    ; -D ARDUINO_T_BEAM_S3_SUPREME
    ; -D ARDUINO_T_PANEL
    -Wignored-qualifiers
    -Wnarrowing
    -Wtype-limits
    ; -Werror
    -Wall
    -Wunused-variable
    -Werror=format
    -Wmissing-field-initializers
    -std=c++11
    -Werror=nonnull

lib_deps = 
    ; creativerobotics/Commander @ ^4.3.0
    ; arduino-libraries/Madgwick @ ^1.2.0
    ; lewisxhe/XPowersLib @ ^0.3.2
    ; thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.2

monitor_filters =
	default
	esp32_exception_decoder
    time

[esp32_base]
extends = env
upload_protocol = esptool
board_upload.wait_for_upload_port = yes
upload_flags =
  --no-stub

[env:esp32dev_arduino]
extends = ${esp32_base}
platform = espressif32@6.12.0
framework = arduino
board = esp32dev

build_flags = 
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=4

[env:esp32c3_arduino]
extends = ${esp32_base}
platform = espressif32@6.12.0
framework = arduino
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
build_flags = 
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=0

[env:esp32s3_arduino]
extends = ${esp32_base}
platform = espressif32@6.12.0
framework = arduino
board = esp32-s3-devkitm-1
; board = esp32s3box
build_flags = 
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DCORE_DEBUG_LEVEL=0

[env:rp2040_arduino]
extends = env
; platform = raspberrypi
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

[env:nrf52840_arduino]
extends = env
platform = nordicnrf52@10.6.0
board = nrf52840_dk_adafruit
framework = arduino
monitor_speed = 115200

upload_protocol = nrfutil
; upload_protocol = nrfjprog
; upload_protocol = jlink

build_flags = 
    ${env.build_flags}
    -DCFG_DEBUG=3 
    -DCFG_LOGGER=0 
    -DCFG_SYSVIEW=1

lib_deps = 
    adafruit/SdFat - Adafruit Fork @ 2.2.3           ;BHI260AP_UpdateFirmware example use
    creativerobotics/Commander @ ^4.3.0               ;bhi260ap_aux_bmm150_bme280_gpio example use

[env:stm32_arduino]
extends = env
platform = ststm32@19.5.0
framework = arduino
board = nucleo_f411re
upload_protocol = stlink

[env:pico_mbed]
extends = env
platform = raspberrypi
framework = arduino
board = pico
