;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
;   https://docs.platformio.org/page/projectconf.html

[platformio]

; ==================== Actuators ====================

; !Haptic Driver
; src_dir = examples/Actuators/Haptic/HapticDrv_DRV2605_Effect
; src_dir = examples/Actuators/Haptic/HapticDrv_DRV2605_Full
; src_dir = examples/Actuators/Haptic/HapticDrv_AW86224_Full

; !LED Driver
; src_dir = examples/Actuators/LED/AW9364_LedDriver

; ==================== IO ====================

; !GPIO Expansion examples
; src_dir = examples/IO/Expander/PCA9570_IoExpander
; src_dir = examples/IO/Expander/XL9555_AdjustBacklight
; src_dir = examples/IO/Expander/XL9555_ExtensionIOInterrupt
; src_dir = examples/IO/Expander/XL9555_ExtensionIORead
; src_dir = examples/IO/Expander/XL9555_ExtensionIOWrite
; src_dir = examples/IO/Expander/XL9555_ExtensionSPI

; ==================== PowerManagement ====================

; !Fuel gauge
; src_dir = examples/PowerManagement/Gauge/AXP2602_GaugeExample
; src_dir = examples/PowerManagement/Gauge/AXP2602_GaugeExample_UDP
; src_dir = examples/PowerManagement/Gauge/BQ27220_GaugeExample

; !PMIC Chargers
; src_dir = examples/PowerManagement/Pmic/BQ25896_Charger
; src_dir = examples/PowerManagement/Pmic/BQ25896_Charger_WebMonitor
; src_dir = examples/PowerManagement/Pmic/SY6970_Charger
; src_dir = examples/PowerManagement/Pmic/SY6970_Charger_WebMonitor


; ==================== Sensors ====================

; !Accelerometer
; src_dir = examples/Sensors/Accelerometer/BMA422_Accelerometer
; src_dir = examples/Sensors/Accelerometer/BMA422_AnyMotion
; src_dir = examples/Sensors/Accelerometer/BMA422_NoMotion
; src_dir = examples/Sensors/Accelerometer/BMA423_Accelerometer
; src_dir = examples/Sensors/Accelerometer/BMA423_AnyMotion
; src_dir = examples/Sensors/Accelerometer/BMA423_DataReadyInterrupt
; src_dir = examples/Sensors/Accelerometer/BMA423_NoMotion
; src_dir = examples/Sensors/Accelerometer/BMA423_StepActivity
; src_dir = examples/Sensors/Accelerometer/BMA423_StepDetector
; src_dir = examples/Sensors/Accelerometer/BMA423_Tap
; src_dir = examples/Sensors/Accelerometer/BMA423_Tilt
; src_dir = examples/Sensors/Accelerometer/BMA456H_Accelerometer
; src_dir = examples/Sensors/Accelerometer/BMA456H_AnyMotion
; src_dir = examples/Sensors/Accelerometer/BMA456H_DataReadyInterrupt
; src_dir = examples/Sensors/Accelerometer/BMA456H_NoMotion
; src_dir = examples/Sensors/Accelerometer/BMA456H_StepActivity
; src_dir = examples/Sensors/Accelerometer/BMA456H_StepDetector
; src_dir = examples/Sensors/Accelerometer/BMA456H_Tap

; !Finger Navigation
; src_dir = examples/Sensors/FingerNavigation/PawA350_MotionSensor

; !IMU - BHI260AP
; src_dir = examples/Sensors/IMU/BHI260AP_6DoF
; src_dir = examples/Sensors/IMU/BHI260AP_Activity
; src_dir = examples/Sensors/IMU/BHI260AP_aux_BMM150
; src_dir = examples/Sensors/IMU/BHI260AP_aux_BMM150_BME280
; src_dir = examples/Sensors/IMU/BHI260AP_aux_BMM150_BME280_Expand_GPIO
; src_dir = examples/Sensors/IMU/BHI260AP_aux_BMM150_euler
; src_dir = examples/Sensors/IMU/BHI260AP_aux_BMM150_quaternion
; src_dir = examples/Sensors/IMU/BHI260AP_Euler
; src_dir = examples/Sensors/IMU/BHI260AP_Expand_GPIO
; src_dir = examples/Sensors/IMU/BHI260AP_InterruptSettings
; src_dir = examples/Sensors/IMU/BHI260AP_Klio_Recognition
; src_dir = examples/Sensors/IMU/BHI260AP_Klio_RecognizeMultiple
; src_dir = examples/Sensors/IMU/BHI260AP_Klio_Selflearning
; src_dir = examples/Sensors/IMU/BHI260AP_Multiple
; src_dir = examples/Sensors/IMU/BHI260AP_Orientation
; src_dir = examples/Sensors/IMU/BHI260AP_StepCounter
; src_dir = examples/Sensors/IMU/BHI260AP_TiltDetector
; src_dir = examples/Sensors/IMU/BHI260AP_UpdateFirmware

; !IMU - BHI360
; src_dir = examples/Sensors/IMU/BHI360_6DoF
; src_dir = examples/Sensors/IMU/BHI360_AnyMotion
; src_dir = examples/Sensors/IMU/BHI360_Euler
; src_dir = examples/Sensors/IMU/BHI360_Multi_Tap
; src_dir = examples/Sensors/IMU/BHI360_NoMotion
; src_dir = examples/Sensors/IMU/BHI360_StepCounter
; src_dir = examples/Sensors/IMU/BHI360_aux_BMM350_BME688_IAQ
; src_dir = examples/Sensors/IMU/BHI360_aux_BMM350_BMP580_BME688
; src_dir = examples/Sensors/IMU/BHI360_aux_BMM350_euler
; src_dir = examples/Sensors/IMU/BHI360_aux_BMM350_quaternion

; !IMU - QMI8658
; src_dir = examples/Sensors/IMU/QMI8658_BlockExample
; src_dir = examples/Sensors/IMU/QMI8658_CalibrationExample
; src_dir = examples/Sensors/IMU/QMI8658_GetDataExample
; src_dir = examples/Sensors/IMU/QMI8658_InterruptBlockExample
; src_dir = examples/Sensors/IMU/QMI8658_InterruptExample
; src_dir = examples/Sensors/IMU/QMI8658_LockingMechanismExample
; src_dir = examples/Sensors/IMU/QMI8658_MadgwickAHRS
; src_dir = examples/Sensors/IMU/QMI8658_MotionDetectionExample
; src_dir = examples/Sensors/IMU/QMI8658_PedometerExample
; src_dir = examples/Sensors/IMU/QMI8658_ReadFromFifoExample
; src_dir = examples/Sensors/IMU/QMI8658_TapDetectionExample
; src_dir = examples/Sensors/IMU/QMI8658_WakeOnMotion
; src_dir = examples/Sensors/IMU/QMI8658_WakeOnMotionCallBackExample

; !Light Sensor
; src_dir = examples/Sensors/LightSensor/CM32181_LightSensor
; src_dir = examples/Sensors/LightSensor/CM32181_LightSensorInterrupt
; src_dir = examples/Sensors/LightSensor/LTR553ALS_Sensor

; !Magnetometer
; src_dir = examples/Sensors/Magnetometer/BMM150_GetDataExample
; src_dir = examples/Sensors/Magnetometer/MagInterface_GetDataExample
; src_dir = examples/Sensors/Magnetometer/QMC5883L_GetDataExample
; src_dir = examples/Sensors/Magnetometer/QMC5883P_GetDataExample
; src_dir = examples/Sensors/Magnetometer/QMC6309_GetDataExample
; src_dir = examples/Sensors/Magnetometer/QMC6310_CalibrateExample
; src_dir = examples/Sensors/Magnetometer/QMC6310_CompassExample
; src_dir = examples/Sensors/Magnetometer/QMC6310_GetDataExample

; !Touch
; src_dir = examples/Sensors/Touch/TouchDrvInterface_Example
; src_dir = examples/Sensors/Touch/TouchDrv_CHSC5816_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_CST3530_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_CST9217_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_CSTxxx_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_FT6232_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_GT911_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_GT9895_GetPoint
; src_dir = examples/Sensors/Touch/TouchDrv_GT9895_GetPoint_LilyGoP4
; src_dir = examples/Sensors/Touch/TouchDrv_HI8561_GetPoint_LilyGoP4

; ==================== Time ====================

; !RTC
; src_dir = examples/Time/PCF85063_AlarmByUnits
; src_dir = examples/Time/PCF85063_ClockOutput
; src_dir = examples/Time/PCF85063_SimpleTime
; src_dir = examples/Time/PCF8563_AlarmByUnits
; src_dir = examples/Time/PCF8563_ClockOutput
; src_dir = examples/Time/PCF8563_SimpleTime
; src_dir = examples/Time/PCF8563_TimeLib
; src_dir = examples/Time/PCF8563_TimeSynchronization
; src_dir = examples/Time/SensorRtcHelperExamples
; src_dir = examples/Time/SensorRtcPosixExample

; ==================== Utilities ====================

; !Custom callback examples
; src_dir = examples/Utilities/CustomCallback/CustomCallbackTouchDrvInterface
; src_dir = examples/Utilities/CustomCallback/CustomCallbackUsageExamples
; src_dir = examples/Utilities/SensorWireHelper

; ==================== Default Config ====================


; !Device envs
default_envs = esp32dev_arduino
; default_envs = esp32s3_arduino
; default_envs = esp32c3_arduino
; default_envs = rp2040_arduino
; default_envs = nrf52840_arduino
; default_envs = stm32_arduino
; default_envs = pico_mbed

; !Test all
; default_envs = esp32dev_arduino , rp2040_arduino , nrf52840_arduino , stm32_arduino , pico_mbed

[env]
lib_extra_dirs = .
upload_speed = 921600
monitor_speed = 115200

build_flags =
    ; -DSENSOR_SDA=3
    ; -DSENSOR_SCL=2
    ; -DSENSOR_IRQ=-1

    -DPMIC_SDA=21
    -DPMIC_SCL=22
    -DPMIC_IRQ=26

    ; -DWIFI_SSID=\"Cisco-A\"
    ; -DWIFI_PASSWORD=\"heweijian55291130\"
    ; -DARDUINO_T_DECK
    ; -DARDUINO_T_AMOLED_191
    ; -DARDUINO_T_AMOLED_191_QWIIC
    ; -DARDUINO_T_AMOLED_241
    ; -DARDUINO_T_AMOLED_147
    ; -DARDUINO_T_DISPLAY_S3_PRO
    ; -DARDUINO_T_DISPLAY_S3
    ; -DARDUINO_T_EPD47_S3
    ; -DARDUINO_T_WATCH_S3_ULTRA
    ; -DARDUINO_T_WATCH_S3
    ; -DARDUINO_T_DECK
    ; -DARDUINO_T_ULTIMA
    ; -DUSE_SPI_INTERFACE=1
    ; -DLOG_PORT=Serial
    ; -DBOSCH_PARSE_DATA_DUMP
    ; -D ARDUINO_T_BEAM_S3_SUPREME
    ; -D ARDUINO_T_PANEL
    -Wignored-qualifiers
    -Wnarrowing
    -Wtype-limits
    ; -Werror
    -Wall
    -Wunused-variable
    -Werror=format
    -Wmissing-field-initializers
    -std=c++11
    -Werror=nonnull

    ; -DUSING_DATA_HELPER
    ; -DCUSTOM_SENSOR_EVB

lib_deps = 
    ; creativerobotics/Commander @ ^4.3.0
    ; arduino-libraries/Madgwick @ ^1.2.0
    ; lewisxhe/XPowersLib @ ^0.3.2
    ; thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.2

monitor_filters =
	default
	esp32_exception_decoder
    time

[esp32_base]
extends = env
upload_protocol = esptool
board_upload.wait_for_upload_port = yes
upload_flags =
  --no-stub

[env:esp32dev_arduino]
extends = ${esp32_base}
platform = espressif32@6.12.0
framework = arduino
board = esp32dev

build_flags = 
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=4

[env:esp32c3_arduino]
extends = ${esp32_base}
platform = espressif32@6.12.0
framework = arduino
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
build_flags = 
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=0

[env:esp32s3_arduino]
extends = ${esp32_base}
platform = espressif32@6.12.0
framework = arduino
board = esp32-s3-devkitm-1
; board = esp32s3box
build_flags = 
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DCORE_DEBUG_LEVEL=0

[env:rp2040_arduino]
extends = env
; platform = raspberrypi
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

[env:nrf52840_arduino]
extends = env
platform = nordicnrf52@10.6.0
board = nrf52840_dk_adafruit
framework = arduino
monitor_speed = 115200

upload_protocol = nrfutil
; upload_protocol = nrfjprog
; upload_protocol = jlink

build_flags = 
    ${env.build_flags}
    -DCFG_DEBUG=3 
    -DCFG_LOGGER=0 
    -DCFG_SYSVIEW=1

lib_deps = 
    adafruit/SdFat - Adafruit Fork @ 2.2.3           ;BHI260AP_UpdateFirmware example use
    creativerobotics/Commander @ ^4.3.0               ;BHI260AP_aux_BMM150_BME280_Expand_GPIO example use

[env:stm32_arduino]
extends = env
platform = ststm32@19.5.0
framework = arduino
board = nucleo_f411re
upload_protocol = stlink

[env:pico_mbed]
extends = env
platform = raspberrypi
framework = arduino
board = pico
