#pragma once

#include "SensorBuildOptUser.h"

#ifndef SENSORLIB_EXCLUDE_ALL
#define SENSORLIB_EXCLUDE_ALL 0
#endif

#ifndef SENSORLIB_EXCLUDE_IMU
#define SENSORLIB_EXCLUDE_IMU SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_ACCELEROMETER
#define SENSORLIB_EXCLUDE_ACCELEROMETER SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_MAGNETOMETER
#define SENSORLIB_EXCLUDE_MAGNETOMETER SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_LIGHT_SENSOR
#define SENSORLIB_EXCLUDE_LIGHT_SENSOR SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_RTC
#define SENSORLIB_EXCLUDE_RTC SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH
#define SENSORLIB_EXCLUDE_TOUCH SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_HAPTIC
#define SENSORLIB_EXCLUDE_HAPTIC SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC
#define SENSORLIB_EXCLUDE_PMIC SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_GAUGE
#define SENSORLIB_EXCLUDE_GAUGE SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_IO_EXPANDER
#define SENSORLIB_EXCLUDE_IO_EXPANDER SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_ACTUATOR
#define SENSORLIB_EXCLUDE_ACTUATOR SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_FINGER_NAVIGATION
#define SENSORLIB_EXCLUDE_FINGER_NAVIGATION SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_WIRE_HELPER
#define SENSORLIB_EXCLUDE_WIRE_HELPER SENSORLIB_EXCLUDE_ALL
#endif

#ifndef SENSORLIB_EXCLUDE_QMI8658
#define SENSORLIB_EXCLUDE_QMI8658 SENSORLIB_EXCLUDE_IMU
#endif

#ifndef SENSORLIB_EXCLUDE_BHI
#define SENSORLIB_EXCLUDE_BHI SENSORLIB_EXCLUDE_IMU
#endif

#ifndef SENSORLIB_EXCLUDE_BHI260
#define SENSORLIB_EXCLUDE_BHI260 SENSORLIB_EXCLUDE_BHI
#endif

#ifndef SENSORLIB_EXCLUDE_BHI260_KLIO
#define SENSORLIB_EXCLUDE_BHI260_KLIO SENSORLIB_EXCLUDE_BHI260
#endif

#ifndef SENSORLIB_EXCLUDE_BHI360
#define SENSORLIB_EXCLUDE_BHI360 SENSORLIB_EXCLUDE_BHI
#endif

#ifndef SENSORLIB_EXCLUDE_BMA4XX
#define SENSORLIB_EXCLUDE_BMA4XX SENSORLIB_EXCLUDE_ACCELEROMETER
#endif

#ifndef SENSORLIB_EXCLUDE_BMA422
#define SENSORLIB_EXCLUDE_BMA422 SENSORLIB_EXCLUDE_BMA4XX
#endif

#ifndef SENSORLIB_EXCLUDE_BMA423
#define SENSORLIB_EXCLUDE_BMA423 SENSORLIB_EXCLUDE_BMA4XX
#endif

#ifndef SENSORLIB_EXCLUDE_BMA456H
#define SENSORLIB_EXCLUDE_BMA456H SENSORLIB_EXCLUDE_BMA4XX
#endif

#ifndef SENSORLIB_EXCLUDE_BMA4XX_EXTRA
#define SENSORLIB_EXCLUDE_BMA4XX_EXTRA SENSORLIB_EXCLUDE_BMA4XX
#endif

#ifndef SENSORLIB_EXCLUDE_BMM150
#define SENSORLIB_EXCLUDE_BMM150 SENSORLIB_EXCLUDE_MAGNETOMETER
#endif

#ifndef SENSORLIB_EXCLUDE_QMC5883L
#define SENSORLIB_EXCLUDE_QMC5883L SENSORLIB_EXCLUDE_MAGNETOMETER
#endif

#ifndef SENSORLIB_EXCLUDE_QMC5883P
#define SENSORLIB_EXCLUDE_QMC5883P SENSORLIB_EXCLUDE_MAGNETOMETER
#endif

#ifndef SENSORLIB_EXCLUDE_QMC6309
#define SENSORLIB_EXCLUDE_QMC6309 SENSORLIB_EXCLUDE_MAGNETOMETER
#endif

#ifndef SENSORLIB_EXCLUDE_QMC6310
#define SENSORLIB_EXCLUDE_QMC6310 SENSORLIB_EXCLUDE_MAGNETOMETER
#endif

#ifndef SENSORLIB_EXCLUDE_CM32181
#define SENSORLIB_EXCLUDE_CM32181 SENSORLIB_EXCLUDE_LIGHT_SENSOR
#endif

#ifndef SENSORLIB_EXCLUDE_LTR553
#define SENSORLIB_EXCLUDE_LTR553 SENSORLIB_EXCLUDE_LIGHT_SENSOR
#endif

#ifndef SENSORLIB_EXCLUDE_PCF8563
#define SENSORLIB_EXCLUDE_PCF8563 SENSORLIB_EXCLUDE_RTC
#endif

#ifndef SENSORLIB_EXCLUDE_PCF85063
#define SENSORLIB_EXCLUDE_PCF85063 SENSORLIB_EXCLUDE_RTC
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_CST226
#define SENSORLIB_EXCLUDE_TOUCH_CST226 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_CST816
#define SENSORLIB_EXCLUDE_TOUCH_CST816 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_CST92XX
#define SENSORLIB_EXCLUDE_TOUCH_CST92XX SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_CST3530
#define SENSORLIB_EXCLUDE_TOUCH_CST3530 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_CSTXXX
#define SENSORLIB_EXCLUDE_TOUCH_CSTXXX SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_CHSC5816
#define SENSORLIB_EXCLUDE_TOUCH_CHSC5816 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_FT6X36
#define SENSORLIB_EXCLUDE_TOUCH_FT6X36 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_GT911
#define SENSORLIB_EXCLUDE_TOUCH_GT911 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_GT9895
#define SENSORLIB_EXCLUDE_TOUCH_GT9895 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_TOUCH_HI8561
#define SENSORLIB_EXCLUDE_TOUCH_HI8561 SENSORLIB_EXCLUDE_TOUCH
#endif

#ifndef SENSORLIB_EXCLUDE_HAPTIC_DRV2605
#define SENSORLIB_EXCLUDE_HAPTIC_DRV2605 SENSORLIB_EXCLUDE_HAPTIC
#endif

#ifndef SENSORLIB_EXCLUDE_HAPTIC_AW86224
#define SENSORLIB_EXCLUDE_HAPTIC_AW86224 SENSORLIB_EXCLUDE_HAPTIC
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC_SY6970
#define SENSORLIB_EXCLUDE_PMIC_SY6970 SENSORLIB_EXCLUDE_PMIC
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC_BQ25896
#define SENSORLIB_EXCLUDE_PMIC_BQ25896 SENSORLIB_EXCLUDE_PMIC
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC_AXP192
#define SENSORLIB_EXCLUDE_PMIC_AXP192 SENSORLIB_EXCLUDE_PMIC
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC_AXP202
#define SENSORLIB_EXCLUDE_PMIC_AXP202 SENSORLIB_EXCLUDE_PMIC
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC_AXP2101
#define SENSORLIB_EXCLUDE_PMIC_AXP2101 SENSORLIB_EXCLUDE_PMIC
#endif

#ifndef SENSORLIB_EXCLUDE_PMIC_AXP517
#define SENSORLIB_EXCLUDE_PMIC_AXP517 SENSORLIB_EXCLUDE_PMIC
#endif

#ifndef SENSORLIB_EXCLUDE_GAUGE_AXP2602
#define SENSORLIB_EXCLUDE_GAUGE_AXP2602 SENSORLIB_EXCLUDE_GAUGE
#endif

#ifndef SENSORLIB_EXCLUDE_GAUGE_BQ27220
#define SENSORLIB_EXCLUDE_GAUGE_BQ27220 SENSORLIB_EXCLUDE_GAUGE
#endif

#ifndef SENSORLIB_EXCLUDE_IO_EXPANDER_XL9555
#define SENSORLIB_EXCLUDE_IO_EXPANDER_XL9555 SENSORLIB_EXCLUDE_IO_EXPANDER
#endif

#ifndef SENSORLIB_EXCLUDE_IO_EXPANDER_PCA9570
#define SENSORLIB_EXCLUDE_IO_EXPANDER_PCA9570 SENSORLIB_EXCLUDE_IO_EXPANDER
#endif

#ifndef SENSORLIB_EXCLUDE_IO_EXPANDER_SPI
#define SENSORLIB_EXCLUDE_IO_EXPANDER_SPI SENSORLIB_EXCLUDE_IO_EXPANDER
#endif

#ifndef SENSORLIB_EXCLUDE_AW9364
#define SENSORLIB_EXCLUDE_AW9364 SENSORLIB_EXCLUDE_ACTUATOR
#endif

#ifndef SENSORLIB_EXCLUDE_PAWA350
#define SENSORLIB_EXCLUDE_PAWA350 SENSORLIB_EXCLUDE_FINGER_NAVIGATION
#endif

#define SENSORLIB_EXCLUDE_BHI_COMMON \
    (SENSORLIB_EXCLUDE_BHI260 && SENSORLIB_EXCLUDE_BHI360)

#define SENSORLIB_EXCLUDE_BMA4XX_COMMON \
    (SENSORLIB_EXCLUDE_BMA422 && SENSORLIB_EXCLUDE_BMA423 && \
     SENSORLIB_EXCLUDE_BMA456H && SENSORLIB_EXCLUDE_BMA4XX_EXTRA)

#define SENSORLIB_EXCLUDE_TOUCH_COMMON \
    (SENSORLIB_EXCLUDE_TOUCH_CST226 && SENSORLIB_EXCLUDE_TOUCH_CST816 && \
     SENSORLIB_EXCLUDE_TOUCH_CST92XX && SENSORLIB_EXCLUDE_TOUCH_CST3530 && \
     SENSORLIB_EXCLUDE_TOUCH_CSTXXX && SENSORLIB_EXCLUDE_TOUCH_CHSC5816 && \
     SENSORLIB_EXCLUDE_TOUCH_FT6X36 && SENSORLIB_EXCLUDE_TOUCH_GT911 && \
     SENSORLIB_EXCLUDE_TOUCH_GT9895 && SENSORLIB_EXCLUDE_TOUCH_HI8561)

#define SENSORLIB_EXCLUDE_RTC_COMMON \
    (SENSORLIB_EXCLUDE_RTC && SENSORLIB_EXCLUDE_PCF8563 && SENSORLIB_EXCLUDE_PCF85063)
